export const LOGIN_SUCCESS="LOGIN_SUCCESS"
export const INVALID_USER="INVALID_USER"
export const LOGOUT="LOGOUT"

export const REGISTER_SUCCESS="REGISTER_SUCCESS"
export const ERROR_IN_REGISTER="ERROR_IN_REGISTER"

export const RETRIVE_USERS="RETRIVE_USERS"
export const ERROR_IN_RETERIVING="ERROR_IN_RETERIVING"


export const DELETE_SUCCESS="DELETE_SUCCESS"
export const ERROR_IN_DELETING="ERROR_IN_DELETING"


export const EDIT_SUCCESS="EDIT_SUCCESS"
export const ERROR_IN_EDITING="ERROR_IN_EDITING"

export const VIEW_SELECTED_USER="VIEW_SELECTED_USER"
export const ERROR_IN_SELECTING="ERROR_IN_SELECTING"

export const SEARCH_DATA_SUCCESS="SEARCH_DATA_SUCCESS"
export const ERROR_IN_SEARCHING="ERROR_IN_SEARCHING"

